version: '2.1'
services:
  hrono-elasticsearch-master:
    image: elasticsearch:5.2.0
    command: "elasticsearch -Enetwork.host=_site_ -Ecluster.name=hrono-cluster -Enode.master=true -Enode.data=false -Ehttp.cors.enabled=true -Ehttp.cors.allow-origin=*"
#    environment:
#      - ES_JAVA_OPTS=-Xmx3g -Xms3g
    ports:
      - "9200:9200"
      - "9300:9300"
    privileged: true
#    sysctls:
#      - vm.max_map_count=262144

  hrono-elasticsearch-slave:
    image: elasticsearch:5.2.0
    command: "elasticsearch -Enetwork.host=_site_ -Ecluster.name=hrono-cluster -Ediscovery.zen.ping.unicast.hosts=hrono-elasticsearch-master"
#    environment:
#      - ES_JAVA_OPTS=-Xmx3g -Xms3g
    links:
      - hrono-elasticsearch-master
    privileged: true
#    sysctls:
#      - vm.max_map_count=262144

  hrono-kibana:
    image: kibana:5.2.0
    ports:
      - "5601:5601"
    links:
      - hrono-elasticsearch-master:elasticsearch

  hrono-elasticsearch-head:
    image: mobz/elasticsearch-head:5
    ports:
      - "9100:9100"
    links:
      - hrono-elasticsearch-master